articles/urls.py
from django.conf.urls import patterns, include, url
from .views import ArticlesListView, ArticleDetailView, ArticlesTaggedView
from .feeds import ArticlesFeed


urlpatterns = patterns('',
    url(r'^$', ArticlesListView.as_view(), name="list"),
    url(r'^tagged/(?P<slug>.*)$', ArticlesTaggedView.as_view(), name="tagged"),
    url(r'^view/(?P<slug>.*)$', ArticleDetailView.as_view(), name="view"),
    url(r'^feed/$', ArticlesFeed(), name="feed"),
)

contacts/urls.py
from django.conf.urls import patterns, include, url
from .views import ContactsView


urlpatterns = patterns('',
    url(r'^$', ContactsView.as_view(), name="home"),
)

core/templatetags/urls.py
from django import template
from django.core.urlresolvers import reverse


register = template.Library()


@register.simple_tag(takes_context=True)
def url_active(context, url, hard=True):
    """
        Usage:
        {% active <urls_name> <equivalent:default=True> %}
        {% active 'admin:login' %}
        {% active 'admin:home' False %}
    """
    request = context['request']
    url = reverse(url)
    if hard:
        if request.path == url:
            return 'active'
    else:
        if request.path.startswith(url):
            return 'active'
    return ''

gordio_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView


urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url="/vcard/"), name="index"),

    url(r'^vcard/$', TemplateView.as_view(template_name="vcard.html"), name="vcard"),
    url(r'^articles/', include('articles.urls', namespace="articles")),
    url(r'^contacts/', include('contacts.urls', namespace="contacts")),
    url(r'^captcha/', include('captcha.urls')),

    url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns('django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', {'url': '/about/'}, name='about'),
    url(r'^(?P<url>.*/)$', 'flatpage'),
)


# Apply media file for development
from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

articles/models.py
from datetime import datetime
from django.db import models
from taggit.managers import TaggableManager


class Article(models.Model):
    slug = models.SlugField(max_length=50)
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=25000)
    created_date = models.DateTimeField(auto_now_add=True)
    edited_date = models.DateTimeField(auto_now=True)
    pub_date = models.DateTimeField(default=datetime.today)
    tags = TaggableManager()

    @property
    def description(self):
        try:
            desc = self.content.split('\n')[0]
        except Exception:
            desc = self.content
        return desc

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('articles:view', (), {'slug': self.slug})

core/models.py
from django.db import models

# Create your models here.

contacts/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail as django_send_mail
from django.utils.translation import ugettext_lazy as _
from captcha.fields import CaptchaField


class ContactsForm(forms.Form):
    email = forms.CharField(label=_("You email"), max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Enter you contact Email'}))
    content = forms.CharField(label=_("You message"), max_length=1000,
        widget=forms.Textarea(attrs={'placeholder': 'Enter you message'}))
    captcha = CaptchaField()

    def send_mail(self):
        return django_send_mail(
            _("{0} New message from site".format(settings.EMAIL_PREFIX)),
            self.cleaned_data['content'],
            self.cleaned_data['email'],
            [manager[1] for manager in settings.MANAGERS]
        )

articles/views.py
from django.views.generic import ListView, DetailView
from .models import Article
from datetime import datetime


class ArticlesListView(ListView):
    model = Article
    context_object_name = 'articles'
    paginate_by = 8

    def get_queryset(self):
        """
        Return Articles greater than pub_date
        """
        return Article.objects.filter(pub_date__lte=datetime.now())


class ArticlesTaggedView(ArticlesListView):
    def get_queryset(self):
        """
        Return Articles tagged 'tag' and greater than pub_date
        """
        return Article.objects.filter(
            tags__slug=self.kwargs.get('slug'),
            pub_date__lte=datetime.now()
        )


class ArticleDetailView(DetailView):
    context_object_name = 'article'

    def get_queryset(self):
        """
        Return Articles greater than pub_date
        """
        return Article.objects.filter(pub_date__lte=datetime.now())

contacts/views.py
from django.views.generic.edit import FormView
from django.contrib import messages
from django.utils.translation import ugettext as _
from .forms import ContactsForm


class ContactsView(FormView):
    template_name = 'contacts/contacts.html'
    form_class = ContactsForm
    success_url = '/'

    def form_valid(self, form):
        try:
            form.send_mail()
        except Exception:
            messages.error(self.request, _("Unknown server error. Please try later."))
        else:
            messages.success(self.request, _("Message has been successfully sent."))

        return super(ContactsView, self).form_valid(form)

core/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/articles/article_detail.html
{% extends "articles/article_list.html" %}
{% load i18n compressed markup %}


{% block title %}{{ article.title|title }} — {{ block.super }}{% endblock title %}

{% block head %}
    {{ block.super }}
    {% compressed_css 'hilightjs' %}
    {% compressed_js 'hilightjs' %}
{% endblock head %}

{% block content %}
    <section class="page">
        <article class="article_detail">
            <h1 class="title">{{ article.title }}</h1>
            <ul class="tags">
                {% for tag in article.tags.all %}
                <li><a href="{% url 'articles:tagged' tag.slug %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
            {{ article.content|markdown }}
            <hr>
            <div id="disqus_thread"></div>
            <noscript>Please enable JavaScript to view the comments.</noscript>
        </article>
    </section>
{% endblock content %}

articles/templates/articles/article_list.html
{% extends "base.html" %}
{% load i18n compressed markup %}


{% block title %}{% trans "Articles" %} — {{ block.super }}{% endblock title %}

{% block head %}
    <meta name="DC.rights" scheme="DCTERMS.URI" content="http://creativecommons.org/licenses/by/4.0/">
    <meta name="DC.rights" content="(cc) 2010-{% now "Y" %} Oleg Gordienko">
    {{ block.super }}
    {% compressed_css 'articles' %}
    {% compressed_js 'articles' %}
    <link rel="alternate" type="application/rss+xml" title="Crazy Web/Django Developer" href="{% url 'articles:feed' %}">
{% endblock head %}

{% block content %}
    <section class="page articles_list">
        {% for a in articles %}
        <article>
            <h1 class="title"><a href="{{ a.get_absolute_url }}">{{ a.title }}</a></h1>
            <ul class="tags">
            {% for tag in a.tags.all %}
                <li><a href="{% url 'articles:tagged' tag.slug %}">{{ tag.name }}</a></li>
            {% endfor %}
            </ul>
            <section class="description">
                {{ a.description|truncatewords:"40"|markdown }}
            </section>
        </article>
        {% empty %}
        <p>{% trans "Sorry. Articles don't exist." %}</p>
        {% endfor %}

        {% include "pagination.html" %}
    </section>
{% endblock content %}

contacts/templates/contacts/contacts.html
{% extends "base.html" %}
{% load i18n staticfiles %}


{% block title %}{% trans "Contacts" %} — {{ block.super }}{% endblock title %}

{% block head %}
  {{ block.super }}
  {% load compressed %}
  {% compressed_css 'contacts' %}

  {% load compressed %}
  {% compressed_js 'contacts' %}
{% endblock head %}

{% block content %}
  <section class="page">
    <div class="send_message contacts">
      <h1 class="title">{% trans "Send message" %}</h1>
      <form action="." method="POST">
        {% csrf_token %}

        {% for field in form %}
            {{ field.label_tag }}
            {{ field.errors }}
            {{ field }}
        {% endfor %}

        <div class="buttons">
          <button class="icon-paperplane send" type="submit">{% trans 'Send' %}</button>
          <button onclick="javascript:window.history.back(-1);return false;">{% trans 'Cancel' %}</button>
        </div>
      </form>
    </div>
    <script>document.getElementById('id_email').focus()</script>
  </section>
{% endblock content %}

templates/base.html
{% load i18n staticfiles %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% trans "Oleg Gordienko (Gordio)" %}{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="{{ STATIC_URL }}favicon.png">

  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  {# Use {{ block.super }} in relative templates #}
  {% block head %}
  {% load compressed %}
  {% compressed_css 'main' %}
  {% endblock head %}
</head>
<body>
  {% include "navigation.html" %}

  {# Django messages framework #}
  {% if messages %}
  <section class="messages">
    {% for message in messages %}
    <div class="message{% if message.tags %} {{ message.tags }}{% endif %}">
      {{ message }}
    </div>
    {% endfor %}
  </section>
  {% endif %}

  <section id="content" class="container">
    {% block content %}
    {% endblock content %}
  </section>

  {#-- Yandex.Metrika counter -#}
  {% if not DEBUG %}
    <div style="display:none;">
      <script type="text/javascript">
        (function(w, c) {
          (w[c] = w[c] || []).push(function() {
            try {
              w.yaCounter11936827 = new Ya.Metrika({id:11936827, enableAll: true, webvisor:true});
            }
            catch(e) { }
          });
        })(window, "yandex_metrika_callbacks");
      </script>
    </div>
    <script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
    <noscript><div><img src="//mc.yandex.ru/watch/11936827" style="position:absolute; left:-9999px;" alt=""></div></noscript>
  {% endif %}
  {#-- /Yandex.Metrika counter -#}
</body>
</html>

templates/navigation.html
{% load i18n staticfiles urls %}
<div class="top-nav-wrap">
  <div class="container">
    <nav class="top-menu">
      <a class="{% url_active 'about' %}" href="{% url 'about' %}">{% trans "About me" %}</a>
      <a class="{% url_active 'articles:list' False %}" href="{% url 'articles:list' %}">{% trans "Articles" %}</a>
      <a class="home {% url_active 'vcard' %}" href="/" data-icon="&#xE602;"></a>
      <a class="disabled" href="#">{% trans "Projects" %}</a>
      <a class="{% url_active 'contacts:home' False %}" href="{% url 'contacts:home' %}">{% trans "Contact" %}</a>
    </nav>
  </div>
</div>

templates/pagination.html
{% load i18n %}

{% if is_paginated %}
  <div class="pagination">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">« {% trans "Previous" %}</a>
    {% else %}
      <span>« {% trans "Previous" %}</span>
    {% endif %}

    <span>{{ page_obj.number }}/{{ page_obj.paginator.num_pages }}</span>

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %} »</a>
    {% else %}
      <span>{% trans "Next" %} »</span>
    {% endif %}
  </div>
{% endif %}

templates/pipeline/css.html
<link rel="stylesheet" type="{{ type }}" href="{{ url }}"{% if media %} media="{{ media }}"{% endif %}{% if title %} title="{{ title|default:"all" }}"{% endif %}{% if charset %} charset="{{ charset }}"{% endif %}>

templates/pipeline/inline_js.html
<script{% if async %} async{% endif %}{% if defer %} defer{% endif %}>{{ source|safe }}</script>

templates/pipeline/js.html
<script src="{{ url }}"{% if async %} async{% endif %}{% if defer %} defer{% endif %}></script>

templates/vcard.html
{% extends "base.html" %}
{% load i18n markup %}


{% block title %}{% trans "VCard" %} — {{ block.super }}{% endblock title %}

{% block head %}
    {{ block.super }}
    {% load compressed %}
    {% compressed_css 'vcard' %}
{% endblock head %}

{% block content %}
  <div id="hcard-Oleg-Gordienko" class="vcard">
    <header>
      <h1 class="fn">Oleg Gordienko</h1>
      <h2 class="work">Web/Django Developer</h2>
    </header>

    <section class="profiles">
      <a class="profile googleplus url" rel="me" href="http://plus.google.com/108016109141914573964/posts" title="Google Plus Profile" aria-hidden="true" data-icon="&#xE607;"></a><a class="profile twitter url" rel="me" href="http://twitter.com/GordioUA/" title="Twitter Profile" aria-hidden="true" data-icon="&#xE608;"></a><a class="profile linkedin url" rel="me" href="http://ua.linkedin.com/in/gordio/" title="LinkedIn Profile" aria-hidden="true" data-icon="&#xE603;"></a><a class="profile github url" rel="me" href="http://github.com/gordio/" title="Github Profile" aria-hidden="true" data-icon="&#xE609;"></a><a class="profile stackoverflow url last" rel="me" href="http://stackoverflow.com/users/1385810/gordio" title="Stackoverflow Profile" aria-hidden="true" data-icon="&#xE600;"></a>
    </section>
    <footer>
        <div class="left">
            <div class="line">
                <a class="tel icon-phone" href="tel:+380976934976">(097) 693-49-76</a>
            </div>
            <div class="line">
                <a class="email icon-mail" href="mailto:me@gordio.pp.ua">me@gordio.pp.ua</a>
            </div>
        </div>
        <div class="right">
            <div class="line">
                <a class="url icon-location" href="http://www.google.com/maps/place/Kryvyi+Rih" target="_blank">Ukraine/Kryvyi Rih</a>
            </div>
            <div class="line">
                <a class="url icon-earth" href="http://gordio.pp.ua/">www.gordio.pp.ua</a>
            </div>
        </div>
    </footer>
  </div>
<img class="qrcode" src="/static/img/qrcode.png" alt="QR Code">
{% endblock content %}